version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/pdtf main.go
        - cp bin/pdtf $GOPATH/bin

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go